name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      label:
        description: Deploy
        required: false
        default: Deploy

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload docker-compose.yml para S3
        run: aws s3 cp docker-compose.yml s3://sc-environments/quickchart/docker-compose.yml --acl private

  deploy:
    needs: prepare
    uses: denoww/github_actions/.github/workflows/rodar_docker_compose_no_ec2.yml@main
    with:
      ec2_com_tag: quickchart
      workdir: /opt/quickchart
      s3_compose_uri: s3://sc-environments/quickchart/docker-compose.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  ligar_load_balancer:
    needs: deploy
    uses: denoww/github_actions/.github/workflows/rodar_comandos_em_todos_ec2_com_tag.yml@main
    with:
      aws_region: us-east-1
      ec2_com_tag: quickchart
      remote_cmd: >-
        curl -fsSL https://gist.githubusercontent.com/denoww/5044b8da36f85afabb920263925684e9/raw |
        sudo -E env HOME="$HOME" bash -s -- --tags "projetos=quickchart" --alb-name "seucondominio-web" --ports "https:3008:http:3008" --tcp-healthy-threshold 3 --tcp-unhealthy-threshold 3 --region "us-east-1" --certificado-https-arn "arn:aws:acm:us-east-1:516862767124:certificate/99570c7a-1fb8-4e70-b340-637f7bcaa535"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
