name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: denoww/github_actions/.github/workflows/rodar_docker_compose_no_ec2.yml@main
    with:
      ec2_com_tag: quickchart
      workdir: /opt/quickchart
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
